apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: postgres-secret
    literals:
      - password=postgres
  - name: rabbitmq-secret
    literals:
      - username=guest
      - password=guest
  - name: auth-service-secret
    literals:
      - database-url=postgresql://postgres:postgres@postgres-auth:5432/auth_db
      - secret-key=devsecretkey1234567890
  - name: book-service-secret
    literals:
      - database-url=postgresql://postgres:postgres@postgres-book:5432/book_db
  - name: inventory-service-secret
    literals:
      - database-url=postgresql://postgres:postgres@postgres-inventory:5432/inventory_db
      - rabbitmq-url=amqp://guest:guest@rabbitmq:5672/
  - name: order-service-secret
    literals:
      - database-url=postgresql://postgres:postgres@postgres-order:5432/order_db
      - rabbitmq-url=amqp://guest:guest@rabbitmq:5672/
  - name: notification-service-secret
    literals:
      - rabbitmq-url=amqp://guest:guest@rabbitmq:5672/

images:
  - name: darko999/auth-service
    newTag: latest
  - name: darko999/book-service
    newTag: latest
  - name: darko999/api-gateway
    newTag: latest
  - name: darko999/inventory-service
    newTag: latest
  - name: darko999/notification-service
    newTag: latest
  - name: darko999/order-service
    newTag: latest
  - name: darko999/frontend
    newTag: latest

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
    target:
      kind: Deployment
      name: "auth-service|book-service|inventory-service|order-service|notification-service|api-gateway|frontend"

  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
    target:
      kind: Deployment
      name: rabbitmq
