tempo:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

storage:
  trace:
    backend: local # Replace with s3/gcs for true production
    local:
      path: /var/tempo/traces

persistence:
  enabled: true
  size: 5Gi

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
