apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstore

resources:
- ../../base

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- literals:
  - password=postgres
  name: postgres-secret
- literals:
  - username=guest
  - password=guest
  name: rabbitmq-secret
- literals:
  - database-url=postgresql://postgres:postgres@postgres-auth:5432/auth_db
  - secret-key=devsecretkey1234567890
  name: auth-service-secret
- literals:
  - database-url=postgresql://postgres:postgres@postgres-book:5432/book_db
  name: book-service-secret
- literals:
  - database-url=postgresql://postgres:postgres@postgres-inventory:5432/inventory_db
  - rabbitmq-url=amqp://guest:guest@rabbitmq:5672/
  name: inventory-service-secret
- literals:
  - database-url=postgresql://postgres:postgres@postgres-order:5432/order_db
  - rabbitmq-url=amqp://guest:guest@rabbitmq:5672/
  name: order-service-secret
- literals:
  - rabbitmq-url=amqp://guest:guest@rabbitmq:5672/
  name: notification-service-secret

images:
- name: darko999/api-gateway
  newName: darko999/api-gateway
  newTag: 03f00a2
- name: darko999/auth-service
  newName: darko999/auth-service
  newTag: 03f00a2
- name: darko999/book-service
  newName: darko999/book-service
  newTag: 03f00a2
- name: darko999/frontend
  newName: darko999/frontend
  newTag: 03f00a2
- name: darko999/inventory-service
  newName: darko999/inventory-service
  newTag: 03f00a2
- name: darko999/notification-service
  newName: darko999/notification-service
  newTag: 03f00a2
- name: darko999/order-service
  newName: darko999/order-service
  newTag: 03f00a2



patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
  target:
    kind: Deployment
    name: auth-service|book-service|inventory-service|order-service|notification-service|frontend
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/livenessProbe/timeoutSeconds
      value: 5
    - op: replace
      path: /spec/template/spec/containers/0/readinessProbe/timeoutSeconds
      value: 5
  target:
    kind: Deployment
    name: auth-service|book-service|inventory-service|order-service|notification-service|frontend
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
    - op: replace
      path: /spec/template/spec/containers/0/livenessProbe/timeoutSeconds
      value: 5
    - op: replace
      path: /spec/template/spec/containers/0/readinessProbe/timeoutSeconds
      value: 5
  target:
    kind: Deployment
    name: api-gateway
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
  target:
    kind: Deployment
    name: rabbitmq
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/livenessProbe/timeoutSeconds
      value: 20
    - op: replace
      path: /spec/template/spec/containers/0/readinessProbe/timeoutSeconds
      value: 20
  target:
    kind: Deployment
    name: rabbitmq
